* Motivation

When using some serialization libraries I have to write code to traverse my data structures and then put each of my struct's fields into the format the serialization library wants, and then I have to do this again in reverse.

This library reduces most of that boilerplate, but only for certain types of data structures. I plan to use it for (copyable, assignable, default constructible) structs with public fields, numbers, enums, std::string, and std::vector. For these data structures, the library defines a generic traversal routine that recursively visits each element, calling a serialization/deserialization function for each.

Since there are many different data structures and many different serialization/deserialization libraries, there are two axes for extension:

| Visitor \\ Type    | number | string | vector | struct1 | struct2 | ... |
|--------------------+--------+--------+--------+---------+---------+-----|
| (generic)          |        |        |        |       2 |       2 |   2 |
| Debug output       |      1 |      1 |      1 |         |         |     |
| Binary serialize   |      1 |      1 |      1 |         |         |     |
| Binary deserialize |      1 |      1 |      1 |         |         |     |
| JSON serialize     |      1 |      1 |      1 |         |         |     |
| JSON deserialize   |      1 |      1 |      1 |         |         |     |
| GUI output         |      1 |      1 |      1 |         |         |     |
| ...                |        |        |        |         |         |     |

I don't want to define every one of these. Instead, each visitor type defines the (1) entries: it has to handle numbers, strings, vectors. Each user-defined struct defines the (2) entries. The library fills in the rest.

I created this library primarily for my own use.

* Installation

This is a header-only library, but if you are want to use the optional JSON component, install picojson:

#+begin_src sh
git submodule init
git submodule update
#+end_src

* Usage

To use any of the visitors, construct one, then call the visit function:

#+begin_src cpp
traverse::BinarySerialize writer;
visit(writer, yourobject);
#+end_src

To define traversal of a user-defined struct:

#+begin_src cpp
struct Point {
    int x;
    int y;
};

TRAVERSE_STRUCT(Point, FIELD(x) FIELD(y))
#+end_src

If the fields aren't public, you will need to declare the visit functions as friends; see traverse.h for details.

** Debug output

The =CoutWriter= writes everything to stdout.

** Binary serialization

The =BinarySerialize= and =BinaryDeserialize= classes write/read to a simple binary format. 
There is no backwards/forwards compatibility, compression, optional fields, data structure sharing, zero-copy, support for multiple programming languages, or other nice features. 

If there are errors during deserialization, the =errors= field will contain them. If the string is empty, there were no errors.

** JSON serialization

The JSON serialize and deserialize uses the [[https://github.com/kazuho/picojson][picojson]] library. The visitors convert /to and from picojson values/, not to and from JSON strings. The caller uses picojson to parse a JSON string into a picojson value, then a deserialization visitor to convert a picojson value into the data structure. In the other direction, the caller uses the serialization visitor to convert a data structure into a picojson value, then the picojson library can stringify that into a JSON string. See the top of traverse-json.h.

When deserializing, the library leaves data unchanged in the object if it does not have new data to place there. If the JSON object does not contain all the fields in the user struct, or if the types don't match, those fields will be left unchanged.

Any errors and warnings during deserialization are written to the =errors= stream. Use a stringstream that captures them; if the string is empty, there were no problems.

** Other serialization

The intent of this library is to define data structure traversal separately from the serialization format, so you can write a visitor class to interface to Protocol Buffers, Thrift, Capn Proto, Flatbuffer, MsgPack, XML, YAML, JSON, or one of many other formats.

* Libraries

I'm using the [[https://github.com/kazuho/picojson][picojson]] library, licensed 2-clause BSD:

#+begin_example
Copyright 2009-2010 Cybozu Labs, Inc.
Copyright 2011-2014 Kazuho Oku
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
#+end_example

